config/routes.rb
Cajon::Application.routes.draw do
  get "sessions/new"

  get "pages/home"
  get "pages/contact"
  get "pages/about"
  
  resources :postcomments, :only => [:create]

  resources :posts do
	resources :postcomments
  end
  
  resources :users do
    resources :posts
  end
  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  
  match '/contact', :to => 'pages#contact'
  match '/services',   :to => 'pages#services'
  match "/postcomments/removeapproval/:id", :to => "postcomments#removeapproval"
  match "/posts/publish/:id", :to => "posts#publish"
  match '/pages/sendmail', :to => 'pages#sendmail'
  
  
  root :to => 'pages#home'
  

  

  
  

end

app/models/user.rb
# == Schema Information
# Schema version: 20101021183927
#
# Table name: users
#
#  id                 :integer         not null, primary key
#  name               :string(255)
#  email              :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  encrypted_password :string(255)
#  salt               :string(255)
#  admin              :boolean
#  description        :text
#  twitter_name       :string(255)
#

class User < ActiveRecord::Base
	has_many :posts,  :dependent => :destroy
	 
	attr_accessor :password
    attr_accessible :name, :email, :password, :password_confirmation, :description, :twitter_name
	
	email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	
    validates :email, :presence     => true,
					  :format       => { :with => email_regex },
					  :uniqueness   => { :case_sensitive => false }
	
	validates :name,  :presence => true,
					  :length => {:maximum => 50}
					   # Automatically create the virtual attribute 'password_confirmation'.
  
    validates :password, :presence     => { :if => :password_required?},
                         :confirmation => { :if => :password_required?},
                         :length       => { :if => :password_required?, :within => 6..40 }
						 
	validates :description, :length => { :maximum => 250 }
						 
	before_save :encrypt_password  # => { :if => :password_is_updated?}
	
	cattr_reader :per_page
    @@per_page = 10
	
	def has_password?(submitted_password)
		encrypted_password == encrypt(submitted_password)
	end
	
	def self.authenticate(email, submitted_password) 
		user = find_by_email(email)
		return nil if user.nil?
		return user if user.has_password?(submitted_password)
	end

    def self.authenticate_with_salt(id, cookie_salt)
      user = find_by_id(id)
      (user && user.salt == cookie_salt) ? user : nil
    end
	

	
	 
	private 
		def encrypt_password
		unless self.password.nil?
			self.salt = make_salt if new_record?
			self.encrypted_password = encrypt(password)
		  end
		end

		def encrypt(string)
			secure_hash("#{salt}--#{string}")
		end
	
		def make_salt
			secure_hash("#{Time.now.utc}--#{password}")
		end

		def secure_hash(string)
			Digest::SHA2.hexdigest(string)
		end
		
    protected
       def password_required?
		  self.new_record?
       end
	   
	   def password_is_updated?
		   true
	   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, :only => [:edit, :update]
  before_filter :correct_user, :only => [:edit, :update]
  before_filter :admin_user, :only => [:new , :create]
  before_filter :admin_user,   :only => :destroy
  

  # GET /users
  # GET /users.xml
  def index
    @users = User.paginate(:page => params[:users_page])
	@posts = Post.where(:published => true).paginate(:page => params[:posts_page], :per_page => 5)
	@title = "Blog"
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])
	@posts = @user.posts.where(:published => true).paginate(:page => params[:page], :per_page => 5)
	@title = @user.name 
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new 
  # GET /users/new.xml
  def new
    @title = "Create a new user"
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end 

  # GET /users/1/edit
  def edit
    @title = "Edit user"
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])
	
    respond_to do |format|
      if @user.save
	    sign_in @user 
		flash[:success] = "You're in"
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
		@title = "Create a new user"
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end 

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
	    flash[:success] = "Profile updated"
        format.html { redirect_to(@user) }
        format.xml  { head :ok }
      else
	    @title = "Edit user"
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy
	flash[:success] = "User deleted"

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end 
   
  private

   def correct_user
     is_correct_user(params[:id])
   end
	
	
end

app/helpers/users_helper.rb
module UsersHelper

	def gravatar_for(user, options = { :size => 50 })
		gravatar_image_tag(user.email.downcase, :alt => user.name,
												:class => 'gravatar',
												:gravatar => options)
    end
  
  
end

app/views/users/_aside.html.erb
<h1>
<%= gravatar_for user, :size => 40 %>
<%= user.name %></h1>

	<%= simple_format user.description %>


<% if !user.twitter_name.nil? %>
	<div id="twitter">
	
	</div>
<% end %>

<script src="/javascripts/jquery.twitter.js" type="text/javascript"></script>
<script type="text/javascript"> 
			$(document).ready(function() {
				$("#twitter").getTwitter({
					userName: "<%= user.twitter_name %>",
					numTweets: 5,
					loaderText: "Loading tweets...",
					slideIn: true,
					slideDuration: 750,
					showHeading: true,
					headingText: "Latest Tweets",
					showProfileLink: true,
					showTimestamp: true
				});
			});
		</script>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<li class="clear">
  <%= gravatar_for user, {:size => 50} %>
  <%= link_to user.name, user, :class => "usertitle" %>
<% if !current_user.nil? %>
  <% if current_user.admin? %>
	<%= link_to "Delete", { :action => "destroy", :id => user }, :confirm => "Are you sure?",
	 					    :title => "Delete #{user.name}", :method => :delete, :class =>"deletelink" %>
  <% end %>
<% end %>
  <div>
	<%= simple_format user.description %>
  </div>
</li>

app/views/users/edit.html.erb
<section class="container paddingbottom standardpadding">
<div class="span-15">
		<div class="columnSpacer">
<h1>Edit profile</h1>
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :twitter_name %>
    <%= f.text_field :twitter_name %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, :rows => 6 %>
  </div>
  
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

<div class="standardpadding">
  <%= gravatar_for @user, :size => 50 %>
  <a href="http://gravatar.com/emails">change</a>
</div>
</div>
</div>
<aside class="span-9 last">
	<%= link_to("Add post", new_post_path, :class => "addpostlink biglink")%>
	<%= link_to("Manage posts", user_posts_path(@user), :class => "managepostlink biglink") %>
</aside>

</section>

app/views/users/index.html.erb
<section class="container paddingbottom standardpadding">
<div class="largeSection span-15">
		<div class="columnSpacer">
			<h1>Decorated World Blog</h1>
			<p>
				This is the <strong>Decorated World</strong> weblog. A place to talk
				about design, development, business and other cool things I spot along the way. 
				Have a read and get involved in the conversation.
			</p>
	<% unless @posts.empty? %>	

		<%= render @posts %>
<%= will_paginate @posts, :param_name => 'posts_page' %>
	<% end %>
	</div>
</div>

<aside class="span-9 last">
<h1>Blog roll</h1>

<ul class="users clear">
  <% @users.each do |user| %>
    <%= render user %>
  <% end %>
</ul>
<%= will_paginate @users, :param_name => 'users_page' %>
</aside>
</section>

app/views/users/new.html.erb
<section class="container paddingbottom standardpadding">
<h1>Create a new user</h1>

<%= form_for(@user) do |f| %>
<%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :rows => 10 %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>
</section>

app/views/users/show.html.erb
<div class="container paddingbottom">
	
<p id="notice"><%= notice %></p>
<section class="largeSection span-15">
	<div class="columnSpacer">
		
<% unless @user.posts.empty? %>	

	<%= render @posts %>

<%= will_paginate @posts %>
<% end %>
</div>
</section>

<aside class="span-9 last">
	<%= render :partial => "aside", :locals => { :user => @user } %>
</aside>
</div>