config/routes.rb
Cajon::Application.routes.draw do
  get "sessions/new"

  get "pages/home"
  get "pages/contact"
  get "pages/about"
  
  resources :postcomments, :only => [:create]

  resources :posts do
	resources :postcomments
  end
  
  resources :users do
    resources :posts
  end
  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  
  match '/contact', :to => 'pages#contact'
  match '/services',   :to => 'pages#services'
  match "/postcomments/removeapproval/:id", :to => "postcomments#removeapproval"
  match "/posts/publish/:id", :to => "posts#publish"
  match '/pages/sendmail', :to => 'pages#sendmail'
  
  
  root :to => 'pages#home'
  

  

  
  

end

app/models/post.rb
# == Schema Information
# Schema version: 20101027185323
#
# Table name: posts
#
#  id         :integer         not null, primary key
#  content    :text
#  title      :string(255)
#  user_id    :integer
#  created_at :datetime
#  updated_at :datetime
#  published  :boolean
#  slug       :text
#

class Post < ActiveRecord::Base
	belongs_to :user
	has_many :postcomments, :dependent => :destroy  
	
	validates :title, :presence => true, :length => {:maximum => 200 }
	validates :user_id, :presence => true 
	validates :slug, :presence => true, :length => { :maximum => 800 }
	validates :content, :length => { :maximum => 10000 }
	
	attr_accessible :title, :content, :published, :slug
	
	default_scope :order => 'posts.created_at DESC'
	
	cattr_reader :per_page
    @@per_page = 10
	
	def publish
	  this.published = true
	  this.save
	end
	 
end

app/controllers/posts_controller.rb
require 'vendor/reversemarkdown/reverse_markdown'

class PostsController < ApplicationController
  before_filter :authenticate, :only => [:new, :create]
  before_filter :correct_user, :only => [:edit, :update, :destroy, :index]

  # GET users/1/posts
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.paginate(:page => params[:page], :per_page => 20)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.xml
  def show
	
    @post = Post.find(params[:id])
	@title = @post.title
	@postcomment = @post.postcomments.new

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @post }
    end
  end
  

  # GET /posts/new
  # GET /posts/new.xml
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
	r = ReverseMarkdown.new
	content = r.parse_string(@post.content)
	@post.content = content
  end

  # POST /posts
  # POST /posts.xml
  def create
    @post = current_user.posts.build(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to(@post, :notice => 'Post created.') }
        format.xml  { render :xml => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.xml
  def update
    @post = Post.find(params[:id])
	published = false
	if  params[:post][:published] == 1
	  published = true
	end

    respond_to do |format|
      if @post.update_attributes(params[:post] )
        format.html { redirect_to(@post, :notice => 'Post updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.xml
  def destroy
	@post = Post.find(params[:id])
    @post.destroy
    flash[:success] = "Post deleted"
    respond_to do |format|
      format.html { redirect_to(user_posts_path(@post.user)) }
      format.xml  { head :ok }
    end
  end
  
  def publish
	@post = Post.find(params[:id])
	@post.published = true
	@post.save
	
	redirect_to(user_posts_path @post.user, :status => "Post published")
	
  end
  
  private 
	def correct_user
	  if params[:user_id].nil?
		@post = Post.find(params[:id])
        @user = @post.user
        is_correct_user(@user.id)
	  else
	    is_correct_user(params[:user_id])
	  end
    end
  
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, :class => "title" %>
  </div>
  <div class="field">
    <%= f.label :slug %>
    <%= f.text_area :slug, :class=>"f wmd-ignore smalltextarea" %>
  </div>
  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>
  <div class="field">
	<%= f.check_box   :published %> 
    <%= f.label  :published %> 
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
 <article>
	<h2>Post preview</h2>
 	<div class="wmd-preview"></div>
 </article> 

<% end %>
	<script>wmd_options = { output: "Html", input: "post_content" };</script>
	<script type="text/javascript"  src="/javascripts/wmd/wmd.js"></script> 

app/views/posts/_post.html.erb
	<article>
		<% if !current_user.nil? %>
	<% if current_user == post.user %>
		<%= link_to "", {:controller => "posts", :action => "edit", :id => post }, :class=> "editLink", :title => "Edit post" %>
	<% end  %>
		<% end %>
		
		<h1><%= link_to post.title, post_path(post) %></h1>
		<span class="nobreak"><span class="postuser"><%= post.user.name %></span> 
		<time datetime="<%= format_iso_date post.created_at %>"><%= format_date_short(post.created_at) %></time></span>
		<div class="commentsummary">
			<%= link_to post.postcomments.where(:approved => true).length.to_s + " comments",  post_path(post) + "#comments"%> <% if post.postcomments.any? and post.postcomments.where(:approved => true).length > 0 %><span>latest by <%= post.postcomments.last.name %></span><% end %>
		</div>
		<div class="postcontent"><%=raw post.content %></div>
	</article>

app/views/posts/edit.html.erb
<section class="container paddingbottom standardpadding">
<h1>Edit post</h1>

<%= render 'form' %>

</section>

app/views/posts/index.html.erb
<section class="container paddingbottom standardpadding">
<h1>Listing posts</h1>

<%= will_paginate @posts %>
<table>

<% @posts.each do |post| %>
  <tr>

    <td><%= link_to post.title, post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, :confirm => 'Are you sure?', :method => :delete %></td>
	<td>
	<% if !post.published? %>

	  <%= link_to 'Publish', { :controller => "posts", :action => "publish", :id => post.id }%>
	<% end %>

	</td>
  </tr>
<% end %>
</table>
<%= will_paginate @posts %>
<br />

<%= link_to 'New Post', new_post_path %>
</section>

app/views/posts/new.html.erb
<section class="container paddingbottom standardpadding">
<h1>New post</h1>

<%= render 'form' %>

</section>

app/views/posts/show.html.erb
<div class="container paddingbottom standardpadding">
<section class="span-15">
	<div class="columnSpacer">
<%= render @post %>

<section id="comments">
	<% if @post.postcomments.where(:approved => true).any?%>
<h2>Comments</h2>
<%= render  @post.postcomments %>
	<% end %>
<h3>Say something!</h3>

<%= form_for @postcomment  do |f| %>
  <% if @postcomment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@postcomment.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @postcomment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :website %>
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :content, "Comment" %>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit "Create comment", :class=> "awesome" %>
  </div>
<%= hidden_field_tag 'post_id', @postcomment.post.id %>

<% end %>


</section>
</div>
</section>

<aside class="span-9 last">
	<%= render :partial => "users/aside", :locals => { :user => @post.user } %>
</aside>
</div>

<script>
	$(document).ready(function(){
		$('#new_postcomment').validate({
			rules: {
						"postcomment[content]": "required"
					},
			messages: {
						"postcomment[content]": "Comment required"
					}
		});
	})
</script>