config/routes.rb
Cajon::Application.routes.draw do
  get "sessions/new"

  get "pages/home"
  get "pages/contact"
  get "pages/about"
  
  resources :postcomments, :only => [:create]

  resources :posts do
	resources :postcomments
  end
  
  resources :users do
    resources :posts
  end
  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  
  match '/contact', :to => 'pages#contact'
  match '/services',   :to => 'pages#services'
  match "/postcomments/removeapproval/:id", :to => "postcomments#removeapproval"
  match "/posts/publish/:id", :to => "posts#publish"
  match '/pages/sendmail', :to => 'pages#sendmail'
  
  
  root :to => 'pages#home'
  

  

  
  

end

app/views/layouts/_header.html.erb
<header class="span-22 last"> 
    <% logo = image_tag("logo.png", :alt => "Sample App", :class => "round") %>
	<%= link_to logo, root_path %>
    <nav>
      <ul>
        <li><%= link_to "Home", root_path %></li>
		<li><%= link_to "Blog roll", users_path %></li>
	    <% if signed_in? %>
	    <li><%= link_to "Profile", current_user %></li>
    	<li><%= link_to "Settings", edit_user_path(current_user) %></li>
	    <% end %>
		<% if signed_in? %>
		<li><%= link_to "Sign out", signout_path, :method => :delete %></li>
		<% else %>
		<li><%= link_to "Sign in", signin_path %></li>
		<% end %>
		<li><%= link_to "Contact", contact_path %></li>
      </ul>
    </nav>
  </header>

app/views/layouts/_stylesheets.html.erb
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
	<!--[if lt IE 9]>
	    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
	    <style>
	    header nav ul { width:62% }
	    </style>
	<![endif]-->  
	
	<%= javascript_include_tag :defaults %>
	<script src="/javascripts/jquery.validate.min.js"></script>
	
	<link href="/stylesheets/blueprint/screen.css" media="screen" rel="stylesheet" type="text/css" /> 
	<link href="/stylesheets/blueprint/print.css" media="print" rel="stylesheet" type="text/css" /> 
	<!--[if lt IE 8]><link href="/stylesheets/blueprint/ie.css" media="screen" rel="stylesheet" type="text/css" /><![endif]--> 
	<link href="/stylesheets/custom.css" media="screen and (min-width: 950px)" rel="stylesheet" type="text/css" /> 
		<link rel="stylesheet" media="screen and (min-width: 800px) and (max-width: 950px)" href="/stylesheets/medium.css" />
<link rel="stylesheet" media="screen and (max-width: 800px)" href="/stylesheets/small.css" />
    <title><%= title %></title>
    <%= csrf_meta_tag %>

    <script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-10007376-6']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

  </head>

<body>

	<header>
	<div class="container"> 
		<h1><span>Decorated World</span></h1>
		<div style="width:50%; float:right" class="small-hide">
		<ul class="profilelinks">
			<% if signed_in? %>
		    <li><%= link_to "Profile", current_user %></li>
	    	<li><%= link_to "Settings", edit_user_path(current_user) %></li>
			<li><%= link_to "Sign out", signout_path, :method => :delete %></li>
			<% else %>
			<li><%= link_to "Sign in", signin_path %></li>
			<% end %>
		</ul>	
		</div>
		<nav>
			 <ul>
				<li><%= link_to "Home", root_path %></li>
				<li><%= link_to "Services", services_path %></li>
				<li><%= link_to "Blog", users_path %></li>
				<li><%= link_to "Contact", contact_path %></li>
			  </ul>
		</nav>
	</div>
	</header>
<section>
	 <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
     <% end %>
    
</section>
	<%= yield %>
	<footer>
	<div class="container"> 
		<div class="a_third left-footer" >
			<span class="primary">Wanna talk?<br/> 
			<strong><a class="phone-link" href="tel://+44-113-3930008">+44 (0)113 3930008</a></strong> | <strong>
			<a class="phone-link" href="tel://+44-7530-611852">+44 (0)7530
			611852</a></strong></span><br/>
			<span class="secondary">Not a big talker? Email us on <a href="mailto:hello@decoratedworld.co.uk">hello@decoratedworld.co.uk</a></span>
		</div>
		<div class="a_third center small-hide medium-hide ">
			<img src="../../images/footerlogoclear.png" alt="logo">
		</div>
		<div class="a_third right-footer">
		<span class="primary"><strong>Find out what's been on our minds.</strong></span><br/>
		<span class="secondary"><%= link_to "Check out the Decorated World blog", users_path%></span>
		</div>
	</div> 
	</footer>

</body>
</html>